package com.example.papergenerationapp.ui.theme

import androidx.compose.ui.graphics.Color
val md_theme_light_primary = Color(0xFF006684)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBEE9FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001F2A)
val md_theme_light_secondary = Color(0xFF4D616C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0E6F2)
val md_theme_light_onSecondaryContainer = Color(0xFF081E27)
val md_theme_light_tertiary = Color(0xFF00668A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC3E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E2C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFE)
val md_theme_light_onBackground = Color(0xFF191C1E)
val md_theme_light_surface = Color(0xFFFBFCFE)
val md_theme_light_onSurface = Color(0xFF191C1E)
val md_theme_light_surfaceVariant = Color(0xFFDCE4E9)
val md_theme_light_onSurfaceVariant = Color(0xFF40484C)
val md_theme_light_outline = Color(0xFF70787D)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F3)
val md_theme_light_inverseSurface = Color(0xFF2E3133)
val md_theme_light_inversePrimary = Color(0xFF68D3FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006684)
val md_theme_light_outlineVariant = Color(0xFFC0C8CD)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF68D3FF)
val md_theme_dark_onPrimary = Color(0xFF003546)
val md_theme_dark_primaryContainer = Color(0xFF004D64)
val md_theme_dark_onPrimaryContainer = Color(0xFFBEE9FF)
val md_theme_dark_secondary = Color(0xFFB4CAD6)
val md_theme_dark_onSecondary = Color(0xFF1F333C)
val md_theme_dark_secondaryContainer = Color(0xFF354A53)
val md_theme_dark_onSecondaryContainer = Color(0xFFD0E6F2)
val md_theme_dark_tertiary = Color(0xFF7BD0FF)
val md_theme_dark_onTertiary = Color(0xFF003549)
val md_theme_dark_tertiaryContainer = Color(0xFF004C69)
val md_theme_dark_onTertiaryContainer = Color(0xFFC3E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1E)
val md_theme_dark_onBackground = Color(0xFFE1E2E4)
val md_theme_dark_surface = Color(0xFF191C1E)
val md_theme_dark_onSurface = Color(0xFFE1E2E4)
val md_theme_dark_surfaceVariant = Color(0xFF40484C)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C8CD)
val md_theme_dark_outline = Color(0xFF8A9297)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1E)
val md_theme_dark_inverseSurface = Color(0xFFE1E2E4)
val md_theme_dark_inversePrimary = Color(0xFF006684)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF68D3FF)
val md_theme_dark_outlineVariant = Color(0xFF40484C)
val md_theme_dark_scrim = Color(0xFF000000)


/*
   Base Colors
   used making Material Theme Builder
 */
val seed = Color(0xFF1296BF)
val Primary = Color(0xFF1296BF)
val CustomColor2 = Color(0xFF689FBD)
val CustomColor5 = Color(0xFF51C7FF)
val light_Primary = Color(0xFF006684)
val light_onPrimary = Color(0xFFFFFFFF)
val light_PrimaryContainer = Color(0xFFBEE9FF)
val light_onPrimaryContainer = Color(0xFF001F2A)
val dark_Primary = Color(0xFF68D3FF)
val dark_onPrimary = Color(0xFF003546)
val dark_PrimaryContainer = Color(0xFF004D64)
val dark_onPrimaryContainer = Color(0xFFBEE9FF)
val light_CustomColor2 = Color(0xFF006688)
val light_onCustomColor2 = Color(0xFFFFFFFF)
val light_CustomColor2Container = Color(0xFFC2E8FF)
val light_onCustomColor2Container = Color(0xFF001E2C)
val dark_CustomColor2 = Color(0xFF77D1FF)
val dark_onCustomColor2 = Color(0xFF003549)
val dark_CustomColor2Container = Color(0xFF004D68)
val dark_onCustomColor2Container = Color(0xFFC2E8FF)
val light_CustomColor5 = Color(0xFF00668A)
val light_onCustomColor5 = Color(0xFFFFFFFF)
val light_CustomColor5Container = Color(0xFFC3E8FF)
val light_onCustomColor5Container = Color(0xFF001E2C)
val dark_CustomColor5 = Color(0xFF7AD0FF)
val dark_onCustomColor5 = Color(0xFF003549)
val dark_CustomColor5Container = Color(0xFF004C69)
val dark_onCustomColor5Container = Color(0xFFC3E8FF)